
# https://github.com/kivy-garden/mapview
# https://mapview.readthedocs.io/en/latest/mapview/

#: import MapView kivy_garden.mapview.MapView

<LiveLocationScreen>:
    name: "LiveLocationScreen"
    MapView:
        id: map
        zoom: 5  # 11
        on_parent:
            self.center_on(-25.4462, -49.2906)
        MapMarker:
            id: marker
            lat: -25.4462
            lon: -49.2906
