

<NotificationScreen>:
    name: "NotificationScreen"
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Notifications"
            font_size: dp(30)
            size_hint_y: None
            height: self.texture_size[1] + dp(20)
        ScrollView:
            GridLayout:
                id: notification_grid
                cols: 1
                height: self.minimum_height
                size_hint_y: None
                orientation: 'lr-bt'






